config/routes.rb
Authdemo::Application.routes.draw do
  root 'homes#index'
  devise_for :admins
  devise_for :users
  devise_scope :user do  
    get "/signin" => "devise/sessions#new"
    get "/signout" => "devise/sessions#destroy"
  end
  resources :users do 
    member do
      get :following, :followers
    end
    end
  resources :messages
  resources :conversations
  resources :requests
  resources :relationships, only: [:create, :destroy]
  resources :users
  resources :admins
  resources :searches
  resources :homes

   

end

app/views/shared/_emergancy.html.haml
= form_tag new_user_path, :method => :get do
  = hidden_field_tag 'current_sign_in_ip'
= image_tag"http://maps.google.com/maps/api/staticmap?size=450x300&sensor=true&zoom=16&markers=#{@user.current_sign_in_ip}%2C#{@user.current_sign_in_ip}"
%br 
IP:
\#{current_user.current_sign_in_ip}

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error_explanation
    .alert.alert-error
      The form contains #{pluralize(object.errors.count, "error")}
    %ul
      - object.errors.full_messages.each do |msg|
        %li
          * #{msg}

app/views/shared/_feed.html.haml
- if @feed_items.any?
  %ol.microposts
    = render partial: 'shared/feed_item', collection: @feed_items
    = will_paginate @feed_items

app/views/shared/_feed_item.html.haml
%li{id: feed_item.id}
  = image_tag current_user.image_url(:small_thumb).to_s
  %span.user
    %br/
  %span.destination
    %b Source:
    = feed_item.source
  %span.destination
    %b Destination:
    = feed_item.destination
  %span.destination
    %b Date:
    = feed_item.date
  %span.timestamp
    %b Time:
  = feed_item.time
  %span.content
    %b Comment:
  = feed_item.content
  %br
  %span.timestamp
    Posted #{time_ago_in_words(feed_item.created_at)} ago.
    - if current_user == feed_item.user
      = link_to "Delete", feed_item ,method: :delete, data: { confirm: "You sure?" }, title: "Delete"

app/views/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Sign in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)
    %br/

app/views/shared/_request_form.html.haml
= submit_tag "Hide Map. . . ", class: "hello"
= submit_tag "Show Map. . . ", class: "hello2"
= form_for(@request) do |f|
  .hell
    = render 'shared/error_messages', object: f.object
    #container
      #instructions
        %label{for: "gmaps-input-address"} Destination:
        %br/
        = f.text_field :destination, placeholder: "Start typing a destination place  ...", type: "text", id: "gmaps-input-address"
        %label{for: "gmaps-input-address"} Source:
        %br/
        = f.text_field :source, placeholder: "Start typing a source place...", type: "text", id: "gmaps-input-address"
        #gmaps-error
        #gmaps-canvas
        %br/
      %label{for: ""} Date of Trip:
      %br/
      = f.text_field :date, 'data-behaviour' => 'datepicker', placeholder: "Enter Date"
      %label{for: ""} Time of Trip:
      %br/
      = f.text_field :time, placeholder: "Time"
      %label{for: ""} Comment:
      %br/
      = f.text_area :content, placeholder: "Comment", align: "center"
      %br/
      = f.submit "Post", class: "btn btn-large btn-primary"

app/views/shared/_stats.html.haml
- @user ||= current_user
.stats
  %a{href: following_user_path(@user)}
    %strong#following.stats
      = @user.followed_users.count
    following
  %a{href: followers_user_path(@user)}
    %strong#followers.stats
      = @user.followers.count
    followers

app/views/shared/_user_info.html.haml
= image_tag current_user.image_url(:thumb).to_s
%h1
  Name:
  \#{current_user.name}
  %br/
  Mobile No: #{current_user.phone_no}
%span
  = link_to "view my profile", current_user
%span
  = pluralize(current_user.requests.count, "Post")