config/routes.rb
Authdemo::Application.routes.draw do
  root 'homes#index'
  devise_for :admins
  devise_for :users
  devise_scope :user do  
    get "/signin" => "devise/sessions#new"
    get "/signout" => "devise/sessions#destroy"
  end
  resources :users do 
    member do
      get :following, :followers
    end
    end
  resources :messages
  resources :conversations
  resources :requests
  resources :relationships, only: [:create, :destroy]
  resources :users
  resources :admins
  resources :searches
  resources :homes

   

end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    %div
      %a{href: "http://railstutorial.org/"} Reference Site
  %nav
    %ul
      %li= link_to "About",   '#'
      %li= link_to "Contact", '#'
      %li
        %a{href: "http://news.railstutorial.org/"} News

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      = link_to "Fuelsaver", root_path, id: "logo"
      %nav
        %ul.nav.pull-right
          %li
            = link_to "Home", root_path
          - if admin_signed_in?
            %li
              = link_to "Log out as Admin", destroy_admin_session_path, :method => :delete
          - if user_signed_in?
            %li
              = link_to "Recent User", users_path
            %li
              = link_to "Emergancy", new_user_path
            %li
              = link_to "Search", searches_path
            %li
              = link_to "Messages", conversations_path
            %li#fat-menu.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
                Account
                %b.caret
              %ul.dropdown-menu
                %li
                  = link_to "Profile" ,current_user
                %li
                  = link_to "Settings" ,edit_user_registration_path
                %li.divider
                %li
                  = link_to "Sign out" ,destroy_user_session_path, :method => :delete
          - else
            %li
              = link_to "Sign in", new_user_session_path

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
    = stylesheet_link_tag "application", media: "all","data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    = favicon_link_tag 'rails.png'
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
    .container
      - flash.each do |key, value|
        = content_tag(:div, value, class: "alert alert-#{key}")
      = yield
      %br/
      %br/
      %br/
      %br/
      %br/
      %br/
      %br/
      %br/
      %br/
      = debug(params) if Rails.env.development?
      = render 'layouts/footer'